// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'html',
      value: '<div class="sidebar-spacer"></div>',
    },
    {
      type: 'link',
      label: 'Descoperă Kulturosfera',
      href: 'https://kulturosfera.com',
      className: 'sidebar-card',
    },
    {
      type: 'link',
      label: 'EduREV',
      href: 'https://edurev.kulturosfera.com',
      className: 'sidebar-card',
    },
    {
      type: 'category',
      label: 'Curs V',
      className: 'sidebar-card',
      link: {
        type: 'generated-index',
        title: 'Curs V',
        description: 'Cursuri clasa a V-a pentru anul școlar 2025-2026',
      },
      items: [{ type: 'autogenerated', dirName: 'c5' }],
    },
    {
      type: 'category',
      label: 'Curs VI',
      className: 'sidebar-card',
      link: {
        type: 'generated-index',
        title: 'Curs VI',
        description: 'Cursuri clasa a VI-a pentru anul școlar 2025-2026',
      },
      items: [{ type: 'autogenerated', dirName: 'c6' }],
    },
    {
      type: 'category',
      label: 'Curs VII',
      className: 'sidebar-card',
      link: {
        type: 'generated-index',
        title: 'Curs VII',
        description: 'Cursuri clasa a VII-a pentru anul școlar 2025-2026',
      },
      items: [{ type: 'autogenerated', dirName: 'c7' }],
    },
    {
      type: 'category',
      label: 'Curs VIII',
      className: 'sidebar-card',
      link: {
        type: 'generated-index',
        title: 'Curs VIII',
        description: 'Cursuri clasa a VIII-a pentru anul școlar 2025-2026',
      },
      items: [{ type: 'autogenerated', dirName: 'c8' }],
    },
    {
      type: 'doc',
      id: 'intro', // Assuming intro.mdx id is 'intro'
      className: 'sidebar-card',
      label: 'Despre Platformă',
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
